### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by jsvde** [trump-fmi/ol-labels#11]
- Extend debug mode (window.debug = true)
- sliders for manual t-value correction
- additional ideas?

**Comment by jsvde** [comment]
ideas:
-- sliders for animation duration?
-- checkboxes for conditional rendering
-- variables for icon rendering?
-- use something like 'demoMode': true in API

**Comment by MisterAI** [comment]
Ich würde mich mal hier ransetzen, wie bereits angekündigt.

**Comment by MisterAI** [comment]
siehe 4c02adc62bb3ce2801d18bedf7ca21d3379a713d

**Comment by MisterAI** [comment]
Ich hab jetzt mal ein bisschen was implementiert. Allerdings hab ich nicht wirklich ne Idee, wie ich das Debug Panel einblenden könnte, sobald `window.labelDebug` auf `true` gesetzt wird. Habt ihr hier Vorschläge @jsvde @jgueth ?

**Comment by MisterAI** [comment]
So, das Ein- und Ausblenden des Debug Panels und der Kreise und die Anpassung der Labelgröße funktioniert jetzt. Es sieht halt noch nicht besonders schön aus. ;)

**Comment by MisterAI** [comment]
Ich hab mich übrigens jetzt entschieden, den debug mode über `window.showDebugMode()` zu starten.
