### ISSUE TITLE
Demo mode

### ISSUE THREAD

**Issue by jsvde** [trump-fmi/ol-labels#12]
provide demo.html (?, could be later be used as openlayers/example)

- should move view to random points on map and use random zoom levels
- animate transitions
- maybe automatically switch between layers?

should be used to demonstrate behavior of labels while move/zoom.

**Comment by jgueth** [comment]
I started to implement a simple demo modus in branch "demo-mode"

**Comment by jgueth** [comment]
Implemented demo mode and intergrated in the debug menu #22
