### ISSUE TITLE
Testing environment

### ISSUE THREAD

**Issue by jsvde** [trump-fmi/ol-labels#3]
All code should be tested.

Openlayers uses mocha, phantom and instanbul for testing, see: [here](https://github.com/openlayers/openlayers/blob/master/package.json) and [here](https://github.com/openlayers/openlayers/tree/master/test)

**Comment by jsvde** [comment]
not necessary due to fork of openlayers

**Comment by dpawlowicz** [comment]
not necessary due to fork of openlayers
