### ISSUE TITLE
Find correlation between t and zoom values

### ISSUE THREAD

**Issue by jsvde** [trump-fmi/ol-labels#4]
We need a table to map the zoom levels to t values that make sense.
Linear or logarithmic?

**Comment by jgueth** [comment]
Manual capture of a suitable min_t value to the zoom level, for overlapping free labels:

**zoom - min_t**
0 - _(no-data-from-label-server)_
1 - _(no-data-from-label-server)_ 
2 - _(no-data-from-label-server)_
3 - _(no-data-from-label-server)_ 
4  -  30
5  - 10
6  -  7
7  -  5
8  -  3
9  -  1
10 -  0.5
11 - 0.3
12 -  0.1
13 - 0.05
14  - 0.00…01 _(infinity)_

**Comment by jsvde** [comment]
final values seem very linear. Please provide a function to calculate the min_t based on current zoom level without a switch, to interpolate between levels.

**Comment by sahinM** [comment]
the provided mathematical function is available on branch #issue8 on the old github repository and is to be reviewed and then ready for migration.
it seems to be a reverse exponential function excluding and approximately to zero as a *min_t* when the *zoom level* get's higher and goes up to *64* as min_t when zoom level is at *4*. the zoomLevels 0-4 are excluded in the function with a min_t value as 4000.

**Comment by sahinM** [comment]
the function is : 
`f(x) = 2^(9-(x-1))`
and the gradient of the curve shows me something like that:
![graph](https://user-images.githubusercontent.com/8367887/27191367-ddb91efe-51f7-11e7-9890-763819993196.png)

**Comment by jgueth** [comment]
The functions looks very good. I tested you sample code in the old git repo and the values fit quite well to the former static map.
